source 'https://rubygems.org'

gem 'httparty', '~> 0.13.7'
gem 'sinatra', '~> 1.4', '>= 1.4.7'
gem 'json', '~> 1.8', '>= 1.8.3'
gem 'tumblr_client', '~> 0.8.5'
gem 'dotenv', '~> 2.1', '>= 2.1.1'
gem 'activerecord'
gem 'sinatra-activerecord', '~> 2.0', '>= 2.0.11'
gem 'rake'
gem 'pg'